version: '3.4'

services:
  greeting:
    image: "miladino/hello-django:${TAG}"
    ports:
      - "80:8000"
    environment:
      - DJANGO_MANAGEPY_COLLECTSTATIC=off
      - DEBUG=False
      - LOG_LEVEL=error
