version: '3.4'

networks:
  public:
  private:

volumes:
  static-content:

services:
  greeting:
    image: miladino/hello-django:1.3
    ports:
      - "80:8000"
    networks:
      private:
        aliases:
          - greeting.local
    environment:
      - DJANGO_MANAGEPY_COLLECTSTATIC=on
      - DEBUG=True
      - LOG_LEVEL=debug
    volumes:
      # would use this volume inside nginx container to serve django static files
      - static-content:/src/greetings/static
      # for dev purposes so deveopers can see changes on the fly
      - ./src:/src
