version: '3.4'

services:
  greeting:
    image: miladino/hello-django:1.3
    ports:
      - "80:8000"
    environment:
      - DJANGO_MANAGEPY_COLLECTSTATIC=off
      - DEBUG=False
      - LOG_LEVEL=error
